version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
    - ..:/workspaces/mud-ladder:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    networks:
    - default

  database:
    image: postgres:17
    restart: unless-stopped
    volumes:
    - postgres-data:/var/lib/postgresql/data
    - ./create-db-user.sql:/docker-entrypoint-initdb.d/create-db-user.sql
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: mud-ladder
    networks:
    - default
    ports:
    - 5432:5432

networks:
  default:

volumes:
  postgres-data:
